name: Test & Build
on:
    push:
        branches: [main]

jobs:
    test-and-build:
        runs-on: ubuntu-latest
        steps:
            # Setup environment
            -   uses: actions/checkout@v4
            -   uses: actions/setup-node@v4
                with:
                    node-version: '20.x'
            -   name: Install dependencies
                run: npm ci
            -   name: Run lint & test
                run: npm test
            -   name: Build
                run: npm run build
